name: CI

on:
    push:
        branches:
            - main
            - dev

    workflow_dispatch:

jobs:
    Deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            # SETUP
            - name: Configure AWS Credentials for Dev
              if: contains(github.ref,'dev')
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Configure AWS Credentials for MAIN
              if: contains(github.ref,'main')
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Installing Nodejs
              uses: actions/setup-node@v2-beta
              with:
                  node-version: "18"

            - name: Installing AWS-CDK
              run: npm install -g aws-cdk

            # ROOT DEPENDENCIES
            - name: Install App Dependencies
              run: npm install --force

            # LAMBDA DEPENDENCIES
            - name: Install Lambdas Dependencies
              run: |
                  cd lambda
                  npm install --force
                  cd ..

            # BUILD
            - name: Build (using Typescript)
              run: npm run build

            # DEPLOYMENT
            - name: Create AWS CloudFormation of All Stacks
              run: cdk synth

            # BOOTSTRAP
            - name: Create AWS CloudFormation of All Stacks
              run: cdk bootstrap

            # DEPLOYMENT
            - name: Deploy Dev Stacks
              if: contains(github.ref,'dev')
              run: |
                  STAGE=dev cdk deploy database-d --require-approval never

            - name: Deploy Main Stacks
              if: contains(github.ref,'main')
              run: |
                  STAGE=main cdk deploy database-m --require-approval never
